# Generated by Django 5.2 on 2025-05-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('general', '一般'), ('librarian', '司書')], default='general', help_text='ユーザーの役割を選択してください。', max_length=10, verbose_name='ロール'),
        ),
    ]
