steps:
  # ステップ 1: Dockerイメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/distributed-library-repo/distributed-library-image",
        "-f",
        "docker/Dockerfile.prod",
        ".",
      ]

  # ステップ 2: Docker イメージを Artifact Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/distributed-library-repo/distributed-library-image",
      ]

  # ステップ 3: Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run",
        "deploy",
        "distributed-library",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/distributed-library-repo/distributed-library-image",
        "--platform",
        "managed",
        "--region",
        "asia-northeast1",
        "--allow-unauthenticated",
        "--set-secrets",
        "SECRET_KEY=projects/$PROJECT_ID/secrets/SECRET_KEY_DISTRIBUTED_LIBRARY/versions/latest",
        "ALLOWED_HOSTS=projects/$PROJECT_ID/secrets/ALLOWED_HOSTS_DISTRIBUTED_LIBRARY/versions/latest",
        "DATABASE_URL=projects/$PROJECT_ID/secrets/DATABASE_URL_DISTRIBUTED_LIBRARY/versions/latest",
      ]

# オプション: ロギング設定
options:
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定
timeout: 600s
