@startuml screen_flow
skinparam defaultFontName "Noto Sans CJK JP"
hide empty description

title 分散型図書管理アプリ 画面遷移図   

[*] --> top
state "トップ画面" as top {
    state "ログイン用トップ画面" as notLogin
    state "一般ユーザー用トップ画面" as user 
    state "司書用トップ画面" as librarian
    notLogin --> user : ログインする
    notLogin --> librarian : ログインする
}

state 本の管理 {
    state 本の登録
}
librarian --> 本の登録
本の登録 --> librarian : 登録完了



state 本の利用 {
    state "本の検索画面" as bookSearch
    state "本の検索結果表示" as searchResult
    state "本の貸出状況確認" as bookStatus
    state "貸出・予約" as borrowAndBook
    state "貸出・予約完了表示" as borrowCompletion
    
    state "貸出・予約状況" as borrowingBooks
    state "返却・予約取消" as returnAndCancelReservation

    ' 本の貸出の流れ
    bookSearch --> searchResult
    searchResult --> bookStatus
    bookStatus --> borrowAndBook
    borrowAndBook --> borrowCompletion
    borrowCompletion --> bookSearch 
    
    ' 本の返却の流れ
    borrowingBooks --> returnAndCancelReservation
    returnAndCancelReservation --> borrowingBooks : 返却・予約取り消し後
}
user --> bookSearch
user --> borrowingBooks


@enduml
