@startuml screen_flow
skinparam defaultFontName "Noto Sans CJK JP"
hide empty description

title 分散型図書管理アプリ 画面遷移図   

[*] --> ホーム画面
state ホーム画面 {
    state ログイン前
    state ログイン後_一般ユーザー
    state ログイン後_司書
    ログイン前 --> ログイン後_司書 : ログインする
    ログイン前 --> ログイン後_一般ユーザー : ログインする
}


ログイン後_司書 --> 本の登録

state 本の登録
本の登録 --> ログイン後_司書 : 登録完了
ログイン後_一般ユーザー --> 本の検索
ログイン後_一般ユーザー --> ユーザーが貸出・予約中の本一覧

state 本の利用 {
    state 本の検索
    state 本の検索結果
    state 貸出状況確認
    state 貸出・予約
    state 貸出・予約完了表示
    state ユーザーが貸出・予約中の本一覧
    state 返却する・予約を取り消す

    ' 本の貸出・予約のフロー
    本の検索 --> 本の検索結果
    本の検索結果 --> 貸出状況確認
    貸出状況確認 --> 貸出・予約
    貸出・予約 --> 貸出・予約完了表示
    

    

}
貸出・予約完了表示 --> ログイン後_一般ユーザー
' 本の返却・予約取り消しのフロー
ユーザーが貸出・予約中の本一覧 --> 返却する・予約を取り消す
返却する・予約を取り消す --> ユーザーが貸出・予約中の本一覧

@enduml
