@startuml er
 skinparam defaultFontName "Noto Sans CJK JP"
 entity "ユーザーマスター" {
   +ID <<PK>>
   +ユーザー名 <<UNIQUE>>
   +メールアドレス
   +パスワード
   +ロール <<一般／司書>>
 }
 
 entity "本マスター" {
   +ID <<PK>>
   +ISBN 
   +タイトル 
   +著者
   +出版日
   +出版社
   +画像用リンク
   +保存場所
   +版数
 }

 entity "貸出・予約データ" {
   +ID <<PK>>
   +ユーザーマスターID <<FK>>
   +本マスターID <<FK>>
   +開始日
   +終了日
   +ステータス <<予約中／貸出中／返却済み>>
 }
 
 "ユーザーマスター" ||--o{ "貸出・予約データ" : ユーザーマスターID
 "本マスター" ||--o{ "貸出・予約データ" : 本マスターID

 @enduml