# Generated by Django 5.2 on 2025-05-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版社')),
                ('published_date', models.DateField(verbose_name='出版日')),
                ('image_url', models.URLField(blank=True, verbose_name='画像用リンク')),
                ('edition', models.PositiveIntegerField(default=1, verbose_name='版数')),
            ],
            options={
                'verbose_name': '本',
                'verbose_name_plural': '本マスター',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '保存場所',
                'verbose_name_plural': '保存場所マスター',
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', '貸出可能'), ('loaned', '貸出中'), ('lost', '廃棄済み')], max_length=20, verbose_name='ステータス')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='書籍')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.storagelocation', verbose_name='保存場所')),
            ],
            options={
                'verbose_name': '蔵書',
                'verbose_name_plural': '蔵書',
            },
        ),
    ]
