# Generated by Django 5.2 on 2025-07-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(blank=True, help_text='任意で数値を入力してください。例えば第2版なら「2」と入力してください。わからなければ空欄のままで構いません。', null=True, verbose_name='版数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, help_text='書籍のカバー画像のURLを入力してください（任意）。', verbose_name='画像用リンク'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13桁の数字をハイフンなしで入力してください。', max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(help_text='YYYY-MM-DDの形式で入力してください。例：2025-01-01', verbose_name='出版日'),
        ),
    ]
