# Generated by Django 5.2 on 2025-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_edition_alter_book_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={'verbose_name': '蔵書', 'verbose_name_plural': '蔵書一覧'},
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('available', '貸出可能'), ('loaned', '貸出中'), ('discarded', '廃棄済み')], max_length=20, verbose_name='状態'),
        ),
    ]
