# Generated by Django 5.2 on 2025-07-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_copy_options_alter_copy_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={'verbose_name': '蔵書', 'verbose_name_plural': '蔵書'},
        ),
    ]
