# Generated by Django 5.2 on 2025-07-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_copy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='本の概要や見どころなどを、利用者向けに簡単に説明してください（任意）。', verbose_name='内容紹介'),
        ),
    ]
