# Generated by Django 5.2 on 2025-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date_precision',
            field=models.CharField(choices=[('unknown', '不明'), ('year', '年'), ('month', '年月'), ('day', '年月日')], default='unknown', help_text='出版日がどこまで正確に分かっているかを選択してください。\n\n例：\n- APIで年月日まで取得できた場合 → 「年月日」の精度が自動設定されます。\n- APIで年月のみ、または年のみ取得できた場合 → 「年月」や「年」の精度が設定されます。\n\u3000※この場合、月や日は「1」に自動補完されています。\n\n正確な出版日が判明した場合は、出版日と精度を「年月日（day）」に更新してください。\n出版日が完全に不明な場合は、「不明（unknown）」を選択してください。', max_length=10, verbose_name='出版日精度'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DDの形式で入力してください。例：2025-01-01', null=True, verbose_name='出版日'),
        ),
    ]
