# Generated by Django 5.2 on 2025-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_published_date_precision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date_precision',
            field=models.CharField(choices=[('unknown', '不明'), ('year', '年'), ('month', '年月'), ('day', '年月日')], default='unknown', help_text='出版日がどこまで正確に分かっているかを選択してください。<br><br>例：<br>- APIで年月日まで取得できた場合 → 「年月日」の精度が自動設定されます。<br>- APIで年月のみ、または年のみ取得できた場合 → 「年月」や「年」の精度が設定されます。<br>\u3000※この場合、月や日は「1」に自動補完されています。<br><br>正確な出版日が判明した場合は、出版日と精度を「年月日」に更新してください。<br>出版日が完全に不明な場合は、「不明」を選択してください。', max_length=10, verbose_name='出版日の精度'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='出版社が不明な場合は空欄にしてもかまいません。', max_length=255, verbose_name='出版社'),
        ),
    ]
