# Generated by Django 5.2 on 2025-07-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_published_date_precision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book', verbose_name='書籍'),
        ),
    ]
