# Generated by Django 5.2 on 2025-08-12 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_copy_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13桁の数字をハイフンなしで入力してください。', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBNは13桁の数字で入力してください（ハイフンなし）。', regex='^\\d{13}$')], verbose_name='ISBN'),
        ),
    ]
